apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-cluster-2
  labels:
    app: redis-cluster
spec:
  serviceName: redis-cluster
  replicas: 3
  selector:
    matchLabels:
      app: redis-cluster-2
      region: jp-tok
      zone: tok04
  template:
    metadata:
      labels:
        app: redis-cluster-2
        antiaffinity: redis-node
        region: jp-tok
        zone: tok04
    spec:
      # ゾーンを指定
      nodeSelector:
        failure-domain.beta.kubernetes.io/zone: tok04
      # ノードに一つだけに限定する
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:	
          - labelSelector:
              matchExpressions:
              - key: antiaffinity
                operator: In
                values:
                - redis-node
            topologyKey: "kubernetes.io/hostname"	
      containers:
      - name: redis
        image: redis:5.0.5
        ports:
        - containerPort: 6379
          name: client
        - containerPort: 16379
          name: gossip
        command: ["/conf/fix-ip.sh", "redis-server", "/conf/redis.conf"]
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - "redis-cli -h $(hostname) ping"
          initialDelaySeconds: 15
          timeoutSeconds: 5
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - "redis-cli -h $(hostname) ping"
          initialDelaySeconds: 20
          periodSeconds: 3
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        volumeMounts:
        - name: conf
          mountPath: /conf
          readOnly: false
        - name: data
          mountPath: /data
          readOnly: false
      volumes:
      - name: conf
        configMap:
          name: redis-cluster
          defaultMode: 0755
  volumeClaimTemplates:
  - metadata:
      name: data
      labels:
        name: redis-cluster
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 100Mi
